spring.application.name=ratelimiter
rate-limiter.leaky-bucket.capacity=10
rate-limiter.leaky-bucket.leak-rate-per-second=1
rate-limiter.token-bucket.capacity=10
rate-limiter.token-bucket.refill-rate-per-second=1
rate-limiter.fixed-window.max-requests=10
rate-limiter.fixed-window.window-size-seconds=60
rate-limiter.sliding-window-log.max-requests=10
rate-limiter.sliding-window-log.window-size-seconds=60
logging.level.root=INFO
logging.level.com.systemdesign.ratelimiter=DEBUG
